### ISSUE TITLE
Commenting with ctrl+/ does not work.

### ISSUE THREAD

**Issue by PLyczkowski** [beefsack/GDScript-sublime#1]
Commenting with ctrl+/ does not work.

**Comment by Spooner** [comment]
Yeah, it doesn't seem to recognise # as a comment at all. Odd, because it looks like the author has copied the code for comments from the Python files...

**Comment by vichug** [comment]
this is still the case...

**Comment by Zamaroht** [comment]
Still :(

**Comment by vichug** [comment]
mmm it would seem that beefsack is no longer maintaining this... is someone willing to fork in order to correct this bug ?? which is way beyond my capabilities...

**Comment by beefsack** [comment]
Hi, apologies for the tardiness on getting to this one.

Implementing commenting support is a standalone feature, all this plugin does at the moment is syntax highlighting and snippets.  Commenting support requires 

I moved away from Sublime Text over a year ago so it'll be unlikely I'll be able to implement this, but PRs are welcome.  I'd suggest people look at other plugins which support the commenting shortcuts if they're looking for examples.

**Comment by Zamaroht** [comment]
Actually I think the issue is more about comments not being highlighted than having a shortcut to comment lines.
Currently every line that starts with # is white, when it should be.. gray I guess.
Is it possible to add that to the syntax highlighting without much hassle?

Thanks for the heads up!

**Comment by PLyczkowski** [comment]
Bump? Anyone managed to fix this?
