### ISSUE TITLE
Would you consider re-licensing this repository?

### ISSUE THREAD

**Issue by arfon** [beefsack/GDScript-sublime#10]
Hello there, we'd love to use this library to syntax-highlight files on GitHub but in order to do so we need this library to have a more permissive license.

If you don't have any particular reason for choosing GPL would you be willing to consider switching this to a more permissive license such as MIT, BSD or Apache 2?

Many thanks
Arfon (GitHub Staff)

**Comment by beefsack** [comment]
Hi @arfon, no worries, now on MIT license.

**Comment by arfon** [comment]
Many thanks @beefsack!
