### ISSUE TITLE
Highlighting bug

### ISSUE THREAD

**Issue by Zylann** [beefsack/GDScript-sublime#13]
I tested the package by downloading latest master from Github, however there is a syntax colouring bug:

![image](https://user-images.githubusercontent.com/1311555/40025896-69409326-57d3-11e8-81a1-c251b62def2f.png)

Not sure what clashes there, signals and arguments seems to cause trouble, then everything else gets coloured like parameters.

**Comment by Muzz** [comment]
Found this bug, and it's because it's using the same regex as static. I'll do a pull request.

**Comment by Muzz** [comment]
Ok fixed that, plus added sync, remote, master and slave.
