### ISSUE TITLE
A version for 3.1

### ISSUE THREAD

**Issue by avencherus** [beefsack/GDScript-sublime#16]
A great pkg.  If this is still being maintained, would really look forward to an update for 3.1, especially for the upcoming static typing.

![sublime_text_2018-10-03_05-13-57](https://user-images.githubusercontent.com/13004169/46386615-2cf95a80-c6cb-11e8-9d1b-3451a1c733d9.png)

**Comment by Cygon** [comment]
Same here!

<img width="569" alt="gdscript-3 1" src="https://user-images.githubusercontent.com/3613175/51983447-f4ab3280-2498-11e9-80cf-f09f21f8d97e.png">

**Comment by beefsack** [comment]
Fixed in #17.
