### ISSUE TITLE
Double backslashes can break quote detection.

### ISSUE THREAD

**Issue by avencherus** [beefsack/GDScript-sublime#24]
![image](https://user-images.githubusercontent.com/13004169/69819493-c789f680-1207-11ea-8a30-d3ad3590a33d.png)

This doesn't come up that often, but when using backslashes in strings, the escape slash can break the highlighting if it is the last thing before the ending quote.

I have been using the following work around.  ;)

![image](https://user-images.githubusercontent.com/13004169/69819525-d4a6e580-1207-11ea-972f-e7c365caa42f.png)

![image](https://user-images.githubusercontent.com/13004169/69819635-03bd5700-1208-11ea-9fe5-306574884d9b.png)

![image](https://user-images.githubusercontent.com/13004169/69819780-454e0200-1208-11ea-91ad-35c012d00f18.png)

**Edit** - Expanded the examples.

**Comment by julfers** [comment]
That was an oversight on my part. Pull request: https://github.com/beefsack/GDScript-sublime/pull/26

**Comment by avencherus** [comment]
Thanks.  Likely no fault of yours, it has been an issue for awhile, I hadn't posted it before because the repo seemed to have gone cold.

Second glancing at my example, that was trimmed down from a code file from quite some time ago, but I see in haste of posting I forgot to remove the > -1 .  😄  (Was originally a line using some kind of find())
